# Generated by Django 4.1 on 2023-08-20 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0002_pricing_planfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.app', verbose_name='APP NAME')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('feature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.appfeature', verbose_name='APP FEATURE NAME')),
                ('pricing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.pricing', verbose_name='PRICING')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
